### ISSUE TITLE
提示“文件取消分享了”

### ISSUE THREAD

**Issue by XcantloadX** [5ime/Lanzou_API#3]
这是用 demo 测试 https://www.lanzous.com/i2xrmcb 返回的结果
```json
{
    "code": 201,
    "msg": "文件取消分享了"
}
```
https://tenapi.cn/lanzou/?url=https://www.lanzous.com/i2xrmcb
原链接有效

**Comment by 5ime** [comment]
请求的时候模拟的是手机UA 用手机测试了一下 的确蓝奏的确返回了文件取消分享 暂时无解

**Comment by XcantloadX** [comment]
我这里电脑手机访问都有效

**Comment by 5ime** [comment]
手机点击下载也能正常下载吗

**Comment by XcantloadX** [comment]
可以

**Comment by 5ime** [comment]
第18行`$d = 'https://www.lanzoux.com/tp/' . $id; `改为`$d = 'https://www.lanzous.com/tp/' . $id;`
由于我这边`lanzous.com`无法访问 所以我写的时候用的`lanzoux.com`

**Comment by XcantloadX** [comment]
OK，可以了，感谢
