### ISSUE TITLE
解析问题

### ISSUE THREAD

**Issue by miguo880** [5ime/Lanzou_API#4]
返回结果显示文件取消分享 但是文件明明在 而且可以通过蓝奏下载  请问这个怎么解决

**Comment by 5ime** [comment]
麻烦发一下蓝奏云分享链接

**Comment by miguo880** [comment]
https://tenapi.cn/lanzou/?url=https://ctgcn.lanzous.com/iPXySob69te&pwd=77pv

**Comment by miguo880** [comment]
还有就是获取到的直连 失效很快

**Comment by 5ime** [comment]
1.因为ipa和其他文件不一样 所以没有适配
2.失效时间是由蓝奏决定的(避免盜链) 代码控制不了

**Comment by miguo880** [comment]
直接下载 https://tenapi.cn/lanzou/?url=https://www.lanzous.com/itahfehy1bc&pwd=d17u&type=down

这种这方式是不是可以避免失效

**Comment by 5ime** [comment]
可以避免 但是短时间内请求次数过多会被蓝奏拉黑

**Comment by miguo880** [comment]
一天500到一千算不算多

**Comment by 5ime** [comment]
不好界定 毕竟蓝奏没有给出详细介绍，建议试验一下。如果被ban 可以使用代理ip

**Comment by miguo880** [comment]
你这直解不会失效吧

**Comment by 5ime** [comment]
建议自建

**Comment by miguo880** [comment]
自建不懂得维护啊
不会失效么

**Comment by 5ime** [comment]
蓝奏云没有大改应该不会失效，如果失效请参考
https://github.com/5ime/Lanzou_API/issues/1

**Comment by miguo880** [comment]
源码就是那个PHP文件是吧

**Comment by 5ime** [comment]
对
