### ISSUE TITLE
有密码似乎解析不了……

### ISSUE THREAD

**Issue by yoval** [5ime/Lanzou_API#7]
https://lanzou.bizha.xyz/?url=https://fuwenyue.lanzoui.com/iYQK2wjuefa&pwd=6666

**Comment by 5ime** [comment]
暂未复现成功

**Comment by yoval** [comment]
恢复解析了，顺便截了屏。用的是虚拟主机.

![lanzou](https://cdn.jsdelivr.net/gh/yoval/TuChuang@main/16380912251721638091225159.png)

**Comment by 5ime** [comment]
可能是你服务器ip被拉黑了？ 项目代码我本地运行/服务器运行均可解析成功

**Comment by yoval** [comment]
应该不是，无密码正常解析
https://lanzou.bizha.xyz/?url=https://fuwenyue.lanzoui.com/icSULwxkioh

**Comment by 5ime** [comment]
> 应该不是，无密码正常解析 https://lanzou.bizha.xyz/?url=https://fuwenyue.lanzoui.com/icSULwxkioh

自行`var_dump($$pwdurl);`调试试试吧
